[Variables]

;Large Launcher Buttons====================

LLT1=Chrome
;Program Name
LLP1=C:\Users\Dael\AppData\Local\Google\Chrome\Application\chrome.exe
;Program Path
LLI1=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\PNG\RockMelt-Icon.png
;Program Icon

LLT2=Steam
LLP2=D:\Program Files (x86)\Steam\Steam.exe
LLI2=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\PNG\Control-Panel-icon.png

LLT3=iTunes
LLP3=D:\Program Files (x86)\iTunes\iTunes.exe
LLI3=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\PNG\Messenger333.png

LLT4=Game Fire
LLP4=C:\Program Files (x86)\Smart PC Utilities\Game Fire\GameFire.exe
LLI4=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\PNG\iTunes2.png

LLT5=Arduino
LLP5=C:\Users\Dael\Downloads\arduino-1.0.2-windows\arduino-1.0.2\arduino.exe
LLI5=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\PNG\steam02.png

LLT6=Firefox
LLP6=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
LLI6=C:\Users\Public\Documents\Winstep\Icons\leopard\Leopard Icons\apps\mozilla-firefox.png

;Small Launcher Buttons===========================

SLT1=Gimp
SLP1=C:\Program Files\GIMP 2\bin\gimp-2.8.exe
SLI1=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\icons\Gimp.ico

SLT2=Illustrator
SLP2=C:\Program Files (x86)\Adobe\Adobe Illustrator CS5.1\Support Files\Contents\Windows\Illustrator.exe
SLI2=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\icons\my computer.ico

SLT3=Premiere Pro
SLP3=C:\Program Files\Adobe\Adobe Premiere Pro CS5.5\Adobe Premiere Pro.exe
SLI3=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\icons\recycle-bin-full.ico

SLT4=After Effects
SLP4=C:\Program Files\Adobe\Adobe After Effects CS5.5\Support Files\AfterFX.exe
SLI4=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\icons\Dolphin_Logo.ico

SLT5=Audition
SLP5=C:\Program Files (x86)\Adobe\Adobe Audition CS5.5\Adobe Audition.exe
SLI5=C:\Users\Albertt\Documents\Rainmeter\Skins\Umbrella\Red Black\Icons\icons\acrobat_reader_cs3.ico

SLT6=MediaEncoder
SLP6=C:\Program Files\Adobe\Adobe Media Encoder CS5.5\Adobe Media Encoder.exe
SLI6=C:\Users\Albertt\Pictures\deonos.ico

;Folder Launcher BUttons=========================

FLP1=C:\Users\Albertt\Marzo\19Marzo
;Folder Path
FLN1=Downloads
;Folder Name

FLP2=C:\Users\Dael\Dropbox
FLN2=Dropbox

FLP3=C:\Users\Dael\Music
FLN3=Music

FLP4=C:\Users\Albertt\Documents\Rainmeter
FLN4=Rainmeter

FLP5=C:\Users\Dael\Videos
FLN5=Videos

FLP6=C:\Users\Albertt\Pictures
FLN6=Pictures

FLP7=C:\Users\Albertt
FLN7=Documents

;Clock Webpages==============================

WN1=Facebook
;Webpage Name
WA1=https:\\facebook.com
;Webpage Address

WN2=Tumblr
WA2=http:\\tumblr.com

WN3=YouTube
WA3=http:\\youtube.com

WN4=deviantART
WA4=http:\\daelnz.deviantart.com

WN5=Google Reader
WA5=http:\\google.com\reader

WN6=Mail
WA6=http:\\mail.yahoo.com

;Misc======================

player=iTunes
Drive=C:


